name: Backend Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # ✅ Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # ✅ Setup Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # ✅ Navigate into backend (if code lives in /backend directory)
      - name: Navigate to backend
        run: cd backend

      # ✅ Build with Maven Wrapper (preferred over plain mvn)
      - name: Build with Maven Wrapper
        run: ./mvnw clean install
